### ISSUE TITLE
Incomplete docs and examples

### ISSUE THREAD

**Issue by valcohen** [MrFrankel/Knockout-Memento#5]
This extension looks very cool but I can't get the basics to work. When I look at the examples, I see a few unexplained items. Here's the most basic example:
### Getting Started:

```
//start using it!
var testSub = ko.observable(50).extend({registerToMS: null});

testSub(100);
testSub(150);

newStack.triggerUndo(); //testSub() === 100
newStack.triggerUndo(); //testSub() === 50
newStack.triggerRedo(); //testSub() === 100
```

1) where is `newStack` defined? I create a knockout model and assign it to a global variable: 

```
var MyViewModel = function( initialData ) {
    this.foo = ko.observable( initialData.foo ).extend({ registerToMS: null });
}
var initialData = { foo: 42 }
var vm = new MyViewModel( initialData );
ko.applyBindings( vm );
```

Now, in the JS console, I can access parts of the viewmodel through the `vm` object: 

```
vm.foo();   // -> 42
```

I'd like to exercise the viewmodel from the console, an in the Getting Started example, I could modify `testSub` like this: `vm.testSub(newValue);`

But, how do I get at the undo stack? `newStack` isn't a global, and I can't find any info on how to control its name or how to expose it.

2) When I look at the docs, I can't find the full set of options I can pass to `registerToMS` or `createNewMStack`.

The module seems very powerful, but I don't have enough to go on to use it. Any help appreciated!

**Comment by mmjr** [comment]
Hey, valcohen, 

Happy to hear your interested in using knockout-memento....
Sorry the examples are not clear enough, defiantly get that sorted soon.

As for your quotations, 
There are two ways to get started with Knockout-Memento
1: create a new stack like so: `var stack1 = ko.msf.createStack();`
this will create a new stack and return an instance of it, this is useful if you wish to create multiple stacks

2: use the default stack like so: `stack1 = ko.msf.getDefaultStack();`
this is useful if you only want one stack and use its default settings.

after getting a reference to a stack you can use the API on it. basic API includes:

```
ko.msf.getDefaultStack().triggerUndo();
ko.msf.getDefaultStack().triggerRedo();
```

```
ko.msf.getDefaultStack().startSequencing();
ko.msf.getDefaultStack().stopSequencing();
```

As for the options to pass to `registerToMs`:
`context` : "this stats an object that will be passed back to any subscriber to an undo or redo on the stack, in case you want to pass some data along, for instance if the observable is a member of an instance of some object and you want a reference to that object when triggering an undo or redo
you can subscribe to a stack after you created one using :

```
stack.subscribeTo(function (data){
    var value = data.value;   
    $('input').val(value);
})
```

where data is an object containing properties as 
`value`: "the value to be set"
`context`: "the context you stated in the registerToMs call"
`subject`: "a reference to the actual observable that has been undo/redo"

As for the options to pass to `createStack`:
`stackLimit`: "a limit to the stack"
`discardUndefined`: "any undefined values inputted are not pushed to the stack, useful for ignoring a initial value"

Note that all these options have default values so you don't have to input them to wokr

Also note that in the sources of this project is a folder name 'demos' which contain working examples you can try out.

Please feel free to contact me if you need any more assistance

**Comment by valcohen** [comment]
Thanks for the quick reply! I'll play around with this today and also check out the demos and see if I can get something working, and I'll let you know if I have any other questions. It looks like a well-thought-out library -- I'd be very happy if I can use this rather than trying to implement this myself!

**Comment by valcohen** [comment]
Well, after exposing the default stack via a property on my viewModel, I got the basics working: I extended a `ko.observable` and was able to set its value and then undo it -- yay! Now I'm stuck at the next step: I need to be able to undo changes to an `observableArray`. But when I extend one of those, like

```
self.ChildStories = ko.observableArray([]).extend({registerToMS: null});
```

I get a JavaScript error:

```
Uncaught TypeError: undefined is not a function 
```

when I try to push a value into that array.

Are `observableArrays` supported? If so, what version of Knockout is required? I'm currently using KO v2.1.0.

If they're not supported, what would you suggest as a workaround? The project I'm working on is a tree control for a content management system that shows a set of nested Categories and the categories and stories attached to each level of category. Categories is an observableArray with a single Category node at the root. Each Category has observableArrays of ChildCategories and ChildStories. 

As I drag a category or story to a different category, I update the observableArrays to keep track of the current children of the category. If the user drags an item to the wrong category, I'd like to be able to undo that action, which involves rolling back the changes to the item's previous and current parent categories' ChildStories or ChildCategories observableArrays.

**Comment by mmjr** [comment]
The version in the latest release doesn't support observableArrays.
However we do have a version that dose which I haven't pushed in yet.
Ill run some unit tests on it and push it in later today.

undo/redo of an observableArray will basically undo/redo any adding/removing of elements within the array.

However, changes in the elements themselves will not be undone unless they are registered observables them self's.

I would recommend creating a single observable for each UI property you wish to expose to undo/redo and bind that observable(variable or array) directly to the view so any change in the observables will immediately effect the UI.

Ill also run the test suit on knockout 2.1.0., never tested it on older version so we will have to wait and see. 

I would recommend updated to a newer version anyway.

**Comment by mmjr** [comment]
I have pushed in a new version 1.2.0 that supports observableArrays.
There is an example and some unit tests in the demos folder.

Registering observableArrays is done like so: 

```
 var list = ko.observableArray([]).extend({registerArrayToMS: options})//can pass null as default
```

Note that changes to observableArrays are registered only on changes to element adding/remove
So use ko.observableArrays function to manipulate the array http://knockoutjs.com/documentation/observableArrays.html.

Also I have run unit tests and demos on knockout.2.1.0 and all seems to work well.

**Comment by valcohen** [comment]
Excellent, thanks! I have a short day today so I may not get to work with the new release; if not I'll work on it Monday and let you know how it turns out. Thanks for the update and the detailed suggestions!

**Comment by valcohen** [comment]
Hm, still not working. I extended two observableArrays with Memento, and I get two problems:
1. If I try to push a value into one of the extended obsArrays by calling `push()` directly on it, like `obsArray.push(value)`, I get `Uncaught TypeError: undefined is not a function`. I have to dereference the obsArray and get the underlying array by adding parens: `obsArray().push(value)`. Not a big deal, but I have to change the way I work with the observableArrays.
2. After making the change in #1, then when I'm dragging an item and dropping it on a UI element that's bound to an observableArray, the `sortable` plugin gives me the same error: `Uncaught TypeError: undefined is not a function`

Sortable works properly until I extend the observableArrays it's using with Memento. I'm using the updated version described and liked from http://www.knockmeout.net/2012/02/revisiting-dragging-dropping-and.html

Can I send you a copy of my page and scripts to see what's going wrong? What's the best way to do that? I see I can attach an image to this comment, but not any other file format including zip.

Thanks, and have a good weekend!

**Comment by mmjr** [comment]
Sure, send them to: Maor.Frankel@sizmek.com

**Comment by valcohen** [comment]
Thanks, I just sent you a sample page and some usage notes from my gmail account (val@valcohen.com). Have a good weekend!

**Comment by mmjr** [comment]
I have viewed the sources and found out the problem.
When registering and observableArray you need to initialize like so:

```
var list = ko.observableArray([]).extend({registerArrayToMS: options})
```

using  `registerArrayToMS` instead of  `registerToMS`

 I will send you back your sources modified and tested, a few notes on the changes there:

A. knockout-Sortable does a several alterations to the arrays when dragging so you should use 
`stack.startSequencing()` at the beginning of knockout-sortable `beforeMove` callback and 
`stack.stopSequencing()` at the end of knockout-sortable `afterMove` callback.
This will group all changes to observables into one undo/redo call

B. In your update function, it would be best to use `arg.item.ContentCategoryIDs.replace`
function instead of  `remove/push`, for better performance 

C. I have added keypress event listeners for 'CTRL-Z' and 'CTRL-Y' so you can easily view changes

Hope this gets you going. 

Have a great weekend!!

**Comment by valcohen** [comment]
Brilliant, this works perfectly now! Thanks so much for the help -- I missed the part where I needed to register the observableArray with a different API call than a regular observable. Unless I missed it somewhere, I still don't see it in the docs -- it will save people time (and save you support headaches) if you add an example at some point.

Thanks for wiring up the start/stopSequencing() calls, and the key handler. 

I'm well on my way -- thanks again for the support, and the super-cool library!
